#ifndef CORE_COREWINDOW_COREWINDOWLIBRARY_H
#define CORE_COREWINDOW_COREWINDOWLIBRARY_H

#include "Global.h"

#if defined(COREWINDOW_LIBRARY)
#  define COREWINDOW_EXPORT Q_DECL_EXPORT
#else
#  define COREWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // CORE_COREWINDOW_COREWINDOWLIBRARY_H
