#ifndef CORE_ACTIONMANAGER_ACTIONMANAGERLIBRARY_H
#define CORE_ACTIONMANAGER_ACTIONMANAGERLIBRARY_H

#include "Global.h"

#if defined(ACTIONMANAGER_LIBRARY)
#  define ACTIONMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define ACTIONMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CORE_ACTIONMANAGER_ACTIONMANAGERLIBRARY_H
