#ifndef CORE_SETTINGMANAGER_SETTINGMANAGERLIBRARY_H
#define CORE_SETTINGMANAGER_SETTINGMANAGERLIBRARY_H

#include "Global.h"

#if defined(SETTINGMANAGER_LIBRARY)
#  define SETTINGMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CORE_SETTINGMANAGER_SETTINGMANAGERLIBRARY_H
